import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { Panel, Pill, StatusBadge } from "../components/Primitives";

const liveCredit = "CLC-LIVE-CB-1790698367";
const contractAddress = "NOT YET DEPLOYED · v1.1.0 CANDIDATE";
const contractSha = "CANDIDATE SHA PENDING";
const evidenceSha = "9ca476ade6c465175ec03e7d1e8361ddd7243367a432943962eb9c6699e44371";

function FlowVisual() {
  const nodes = [
    ["01", "Credit", "Terms frozen"],
    ["02", "Evidence", "SHA verified"],
    ["03", "Examination", "Objective checks"],
    ["04", "Challenge", "Bounded question"],
    ["05", "Consensus", "One adjudication"],
    ["06", "Settlement", "Deterministic gate"]
  ];
  return <div className="flow-visual" aria-label="ClearLC documentary settlement flow">{nodes.map(([number, title, detail], index) => <div className={`flow-node ${index === 5 ? "flow-node-final" : ""}`} key={title}><span className="flow-node-number">{number}</span><span className="flow-node-icon" aria-hidden="true">{index === 0 ? "□" : index === 1 ? "▤" : index === 2 ? "⊙" : index === 3 ? "◇" : index === 4 ? "◎" : "✓"}</span><strong>{title}</strong><small>{detail}</small>{index < nodes.length - 1 ? <span className="flow-connector" aria-hidden="true" /> : null}</div>)}</div>;
}

function PublicSection({ eyebrow, title, children, id }: { eyebrow: string; title: string; children: ReactNode; id?: string }) {
  return <section className="public-section" id={id}><div className="public-section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</section>;
}

export function PublicLandingPage() {
  return <div className="public-landing">
    <section className="public-hero" id="product"><div className="public-hero-copy"><span className="eyebrow">Documentary settlement infrastructure</span><h1>Documentary settlement <em>without arbitrary refusal.</em></h1><p>ClearLC freezes documentary terms, authenticates evidence, isolates objective examination, and sends only genuinely semantic disputes to GenLayer consensus.</p><div className="public-hero-actions"><Link className="button button-primary" to="/app">Launch ClearLC <span aria-hidden="true">↗</span></Link><Link className="button button-secondary" to={`/app/credits/${liveCredit}/proof`}>Explore candidate proof</Link></div><div className="public-trust-row"><span>Studio-dev · chain 61997</span><span>v1.1.0 candidate</span><span>34 methods</span><span>Case B fixture</span></div></div><div className="public-hero-visual"><div className="visual-label"><span>Protocol path</span><span>candidate state</span></div><FlowVisual /><div className="visual-proof"><span className="visual-proof-dot" /> Evidence SHA fixture verified <span>·</span> Live payout proof pending</div></div></section>

    <div className="public-proof-strip"><div><span className="eyebrow">Live network</span><strong>Studio-dev · 61997</strong></div><div><span className="eyebrow">Source integrity</span><strong>SHA-bound contract</strong></div><div><span className="eyebrow">Consensus scope</span><strong>Bounded semantic only</strong></div><div><span className="eyebrow">Qualification</span><strong>16/16 fee profile</strong></div><div><span className="eyebrow">Case B</span><strong>Settled in accounting</strong></div></div>

    <PublicSection eyebrow="The problem" title="Documentary payment disputes should be verifiable."><div className="problem-grid"><article><span className="problem-index">01</span><h3>Ambiguous refusal</h3><p>A vague discrepancy claim can become a payment veto when the rule, evidence, and consequence are not separated.</p></article><article><span className="problem-index">02</span><h3>Mutable evidence</h3><p>A document URL is transport. Its authenticated identity must be frozen by authority, version, byte length, and hash.</p></article><article><span className="problem-index">03</span><h3>Opaque adjudication</h3><p>Semantic interpretation should answer one bounded question, not decide the amount, recipient, deadline, or state transition.</p></article></div></PublicSection>

    <PublicSection id="how-it-works" eyebrow="How ClearLC works" title="Certainty before semantics."><div className="process-grid"><div><span>01</span><strong>Freeze terms</strong><p>Credit identity, parties, amount, deadlines, requirements, and ruleset become canonical state.</p></div><div><span>02</span><strong>Bind evidence</strong><p>Authenticated documentary bytes are committed to a versioned presentation.</p></div><div><span>03</span><strong>Examine objective facts</strong><p>Identity, dates, authority, and deterministic checks are evaluated before consensus.</p></div><div><span>04</span><strong>Challenge discrepancy</strong><p>A formal claim is tied to one requirement, presentation, and frozen evidence set.</p></div><div><span>05</span><strong>Bounded adjudication</strong><p>GenLayer evaluates only whether the asserted discrepancy is materially supported.</p></div><div><span>06</span><strong>Settle deterministically</strong><p>State legality and accounting gates remain contract-controlled.</p></div></div></PublicSection>

    <PublicSection id="security" eyebrow="The semantic boundary" title="Consensus has one narrow job."><div className="boundary-grid"><div className="boundary-column boundary-deterministic"><div className="boundary-heading"><span className="boundary-mark">D</span><div><span className="eyebrow">Deterministic</span><h3>What the contract owns</h3></div></div>{["Credit identity and amount", "Parties and deadlines", "Evidence hash and version", "State legality and replay protection", "Settlement eligibility and accounting"].map((item) => <div className="boundary-item" key={item}><span>✓</span>{item}</div>)}</div><div className="boundary-column boundary-semantic"><div className="boundary-heading"><span className="boundary-mark">G</span><div><span className="eyebrow">GenLayer</span><h3>What consensus interprets</h3></div></div><p>Whether the asserted discrepancy is materially supported by the frozen documentary requirement and authenticated evidence.</p><div className="boundary-callout">One question · one fingerprint · one adjudication</div></div></div></PublicSection>

    <PublicSection id="live-proof" eyebrow="v1.1.0 candidate · proof boundary" title="A cash-safe release candidate you can inspect."><div className="live-proof-card"><div className="live-proof-main"><div className="live-proof-id"><span className="eyebrow">Credit ID</span><code>{liveCredit}</code><Pill tone="warning">CANDIDATE</Pill></div><h3>Semantic adjudication stays separate from cash routing.</h3><p>This controlled fixture demonstrates the bounded discrepancy decision. It does not claim a live payout or refund before a new deployment exists.</p><div className="live-proof-facts"><div><span>Decision</span><strong>INVALID_DISCREPANCY</strong></div><div><span>Reason</span><strong>REQUIRED_CONTENT_PRESENT</strong></div><div><span>Cash path</span><strong>BENEFICIARY_PAYOUT / APPLICANT_REFUND</strong></div><div><span>Live proof</span><strong>PENDING DEPLOYMENT</strong></div></div></div><div className="live-proof-side"><Pill tone="warning">NOT YET DEPLOYED</Pill><span className="live-proof-line" /><span className="eyebrow">Candidate protocol</span><strong>One native GEN exit</strong><small>Actual beneficiary and applicant balance proofs remain pending deployment.</small><Link className="button button-primary" to={`/app/credits/${liveCredit}/proof`}>View Candidate Proof &amp; Audit</Link></div></div></PublicSection>

    <PublicSection eyebrow="Integrity by design" title="Every claim leaves a trail."><div className="integrity-grid"><div><strong>SHA-256 identity anchors</strong><p>Evidence identity is bound to immutable metadata, not inferred from a mutable transport URL.</p><code>{evidenceSha.slice(0, 18)}…</code></div><div><strong>Versioned presentations</strong><p>Requirements, evidence, and presentation versions remain reconstructable after a cure or amendment.</p><code>v1 · canonical binding</code></div><div><strong>No result shopping</strong><p>The live qualification accepted the first valid finalized semantic result after one adjudication attempt.</p><code>attempts: 1 · shopping: 0</code></div></div></PublicSection>

    <PublicSection eyebrow="Built for integration" title="A protocol surface reviewers can verify."><div className="developer-grid"><div><span className="eyebrow">Contract</span><code>{contractAddress}</code><small>33 public methods · source verified</small></div><div><span className="eyebrow">Source</span><code>{contractSha}</code><small>Frozen canonical contract</small></div><div><span className="eyebrow">Network</span><strong>Studio-dev / chain 61997</strong><small>Runner: py-genlayer 5jyc</small></div><div className="developer-actions"><Link className="button button-secondary" to="/docs">Read docs</Link><a className="button button-secondary" href="https://github.com/GIFTEDLOV/ClearLC" target="_blank" rel="noreferrer">View GitHub</a></div></div></PublicSection>
  </div>;
}

export function DocsPage() {
  return <div className="public-docs"><div className="public-docs-hero"><span className="eyebrow">Integration notes</span><h1>Build around facts, not assertions.</h1><p>ClearLC exposes a canonical read/write lifecycle for documentary credits, evidence, bounded discrepancy adjudication, and deterministic settlement.</p><div className="public-hero-actions"><Link className="button button-primary" to="/app">Open Trade Desk</Link><Link className="button button-secondary" to="/">Back to overview</Link></div></div><div className="docs-grid public-doc-grid"><Panel eyebrow="Read path" title="Canonical data flow"><ol className="numbered-list"><li>Read credit and frozen version.</li><li>Read requirements and requirement matrix.</li><li>Read evidence by immutable ID, not URI.</li><li>Read discrepancy and adjudication fingerprints.</li><li>Derive business consequence locally from canonical state.</li></ol></Panel><Panel eyebrow="Write path" title="Transaction discipline"><ol className="numbered-list"><li>Precondition read.</li><li>Prepare and quote fees.</li><li>Wallet approval.</li><li>Broadcast exactly once.</li><li>Persist the exact hash before polling.</li><li>Finalize, check execution result, then canonical readback.</li></ol></Panel><Panel eyebrow="Protocol boundary" title="Semantic authority"><p className="panel-intro">GenLayer returns only VALID_DISCREPANCY, INVALID_DISCREPANCY, or INCONCLUSIVE plus a bounded reason code. It never returns a payment amount, recipient, address, deadline, or state transition.</p></Panel></div><div className="public-doc-note"><span className="eyebrow">Need the application</span><strong>Inspect the verified Case B in the operational workspace.</strong><Link className="text-link" to={`/app/credits/${liveCredit}/proof`}>Open Proof &amp; Audit →</Link></div></div>;
}
